#!/usr/bin/env bash
# Would display numbers from 1 to 100 in list format.
#   Display "FizzBuzz" when the number is a multiple of 3 and 5.
#   Display "Fizz" when the number is a multiple of 3.
#   Display "Buzz" when the number is a multiple of 5.
#   Otherwise, display the number.

for fnum in {1..100}
do
  if (( fnum % 3 == 0 && fnum % 5 == 0 ))
  then
    echo "FizzBuzz"
  elif (( fnum % 3 == 0 ))
  then
    echo "Fizz"
  elif (( fnum % 5 == 0 ))
  then
    echo "Buzz"
  else
    echo "$fnum"
  fi
done
