#!/usr/bin/env bash
# Would display "Best School" 10 times using a while loop.
# And on the 9th iteration, would display "Hi" before "Best School".

f=0

while [ $f -lt 10 ]
do
  if [ $f -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( f++ ))
done
