#!/usr/bin/env bash
# Would display the contents of the current directory in list format.
# And would only display the part of the name after the first dash. 

flist=$(ls)
for f in $flist; do
  echo "$f" | cut -d '-' -f2
done
